#!/usr/bin/env python3
"""
Auto Generate Training Data - Profitable Data Generator
自动生成训练数据 - 赚钱版数据生成器
"""

import os
import sys
import logging
from pathlib import Path

# Add project path
sys.path.insert(0, str(Path(__file__).parent))

# Setup logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s"
)

logger = logging.getLogger("AutoGenerateData")


def main():
    """Main function to auto-generate training data"""
    logger.info("\n" + "=" * 70)
    logger.info("Auto Generate Training Data - Profitable Data Generator")
    logger.info("自动生成训练数据 - 赚钱版数据生成器")
    logger.info("=" * 70)

    try:
        from data_generator import (
            BinanceDataLoader,
            FeatureEngineer,
            LabelGenerator
        )

        # Step 1: Find available CSV files
        logger.info("\n[Step 1/4] Scanning data directory...")
        data_dir = Path("data")
        if not data_dir.exists():
            logger.error(f"Data directory not found: {data_dir}")
            return False

        csv_files = list(data_dir.glob("BTCUSDT*.csv"))
        if not csv_files:
            logger.error("No BTCUSDT CSV files found in data directory")
            return False

        logger.info(f"Found {len(csv_files)} BTCUSDT data files")
        for f in csv_files:
            logger.info(f"  - {f.name}")

        # Select the first file
        csv_file = str(csv_files[0])
        logger.info(f"\nUsing file: {csv_file}")

        # Step 2: Load data
        logger.info("\n[Step 2/4] Loading market data...")
        loader = BinanceDataLoader()
        df = loader.load_data_from_csv(csv_file)
        logger.info(f"Successfully loaded {len(df)} records")

        # Step 3: Calculate factors
        logger.info("\n[Step 3/4] Calculating institutional-grade factors...")
        engineer = FeatureEngineer()
        df_with_factors = engineer.calculate_all_factors(df)

        factor_count = len(df_with_factors.columns) - len(df.columns)
        logger.info(f"Calculated {factor_count} Alpha factors")

        # Step 4: Generate labels
        logger.info("\n[Step 4/4] Generating training labels...")
        generator = LabelGenerator()
        df_with_labels = generator.generate_all_labels(df_with_factors)

        label_count = len(df_with_labels.columns) - len(df_with_factors.columns)
        logger.info(f"Generated {label_count} label types")

        # Statistics
        logger.info("\n" + "=" * 70)
        logger.info("Data Generation Complete!")
        logger.info("=" * 70)

        logger.info(f"\nFinal data shape: {df_with_labels.shape}")
        logger.info(f"Total columns: {len(df_with_labels.columns)}")

        # Count missing values
        total_cells = df_with_labels.size
        missing_cells = df_with_labels.isna().sum().sum()
        missing_pct = missing_cells / total_cells * 100
        logger.info(f"Missing values: {missing_cells}/{total_cells} ({missing_pct:.2f}%)")

        # Label statistics
        if "triple_barrier_label" in df_with_labels.columns:
            labels = df_with_labels["triple_barrier_label"].dropna()
            logger.info(f"\nTriple barrier label distribution:")
            dist = labels.value_counts().to_dict()
            for k, v in sorted(dist.items()):
                logger.info(f"  {k}: {v} ({v/len(labels)*100:.1f}%)")

        if "trend_label" in df_with_labels.columns:
            trends = df_with_labels["trend_label"].dropna()
            logger.info(f"\nTrend label distribution:")
            dist = trends.value_counts().to_dict()
            for k, v in sorted(dist.items()):
                logger.info(f"  {k}: {v} ({v/len(trends)*100:.1f}%)")

        # Save output
        output_file = "data/generated_training_data.csv"
        logger.info(f"\nSaving complete dataset to: {output_file}")
        df_with_labels.to_csv(output_file)

        # Save sample
        sample_file = "data/generated_training_data_sample.csv"
        logger.info(f"Saving sample (200 rows) to: {sample_file}")
        df_with_labels.head(200).to_csv(sample_file)

        # Column categories
        original_cols = df.columns.tolist()
        factor_cols = [c for c in df_with_factors.columns if c not in original_cols]
        label_cols = [c for c in df_with_labels.columns if c not in df_with_factors.columns]

        logger.info("\n" + "=" * 70)
        logger.info("Generated Data Summary")
        logger.info("=" * 70)

        logger.info(f"\n1. Original OHLCV: {len(original_cols)} columns")
        if len(original_cols) <= 10:
            logger.info(f"   {original_cols}")
        else:
            logger.info(f"   {original_cols[:10]}... (+{len(original_cols)-10} more)")

        logger.info(f"\n2. Alpha Factors: {len(factor_cols)} columns")
        if len(factor_cols) <= 15:
            logger.info(f"   {factor_cols}")
        else:
            logger.info(f"   {factor_cols[:15]}... (+{len(factor_cols)-15} more)")

        logger.info(f"\n3. Training Labels: {len(label_cols)} columns")
        if len(label_cols) <= 15:
            logger.info(f"   {label_cols}")
        else:
            logger.info(f"   {label_cols[:15]}... (+{len(label_cols)-15} more)")

        logger.info("\n" + "=" * 70)
        logger.info("🎉 Training data generation complete!")
        logger.info("=" * 70)
        logger.info("\nNext steps:")
        logger.info("  - Use data/models_features.py to train ML models")
        logger.info("  - Use rl/trainer.py to train RL agents")
        logger.info("  - Use strategy/ to backtest trading strategies")
        logger.info(f"\nFiles created:")
        logger.info(f"  - {output_file} (full dataset)")
        logger.info(f"  - {sample_file} (sample)")

        return True

    except Exception as e:
        logger.error(f"\nError: {e}")
        import traceback
        logger.error(f"Traceback: {traceback.format_exc()}")
        return False


if __name__ == "__main__":
    success = main()
    sys.exit(0 if success else 1)
